---
properties:
  type: object
  EksCtlConfiguration:
    $ref: '#/definitions/EksCtlConfiguration'

definitions:

  EksCtlConfiguration:
    additionalProperties: false
    properties:
      Create:
        $ref: '#/definitions/Create'
        $schema: http://json-schema.org/draft-04/schema#

  Create:
    additionalProperties: false
    javaInterfaces: [ 'com.walmartlabs.concord.plugins.tool.ToolCommand' ]
    properties:
      Cluster:
        $ref: '#/definitions/Cluster'
        $schema: http://json-schema.org/draft-04/schema#
    type: object

  Cluster:
    additionalProperties: false
    properties:
      configFile:
        type: string
      kubeConfig:
        type: string
    type: object      
